### ISSUE TITLE
explore the endpoints on wine.com api and generate the final object with a list of wines per preferences

### ISSUE THREAD

**Issue by megh0682** [megh0682/group_project#1]
**API ENDPOINTS**

[ ] - Root level category for wine finder - 

`curl -X GET -H "term: mondavi" -H "size: 5" -H "offset: 0" -H "apikey: 007fe7ab34275330c97077856e7a5644" -H "Cache-Control: no-cache" -H "Postman-Token: d679164f-0612-4acd-0fb7-8ca200e008ff" "http://services.wine.com/api/beta2/service.svc/json/categorymap?filter=categories(490)&apikey=007fe7ab34275330c97077856e7a5644"`

> Wine Type Preference

1. Red Wine (124)
2. White Wine(125)
3. Champagne & Sparkling(123)
4. Rose Wine(126)
5. Dessert, Sherry & Port(128)
6. Sake(134)

> Varietal Preference ( we can get a list of varietals here)

1. Cabernet Sauvignon(139)
2. Chardonnay(140)

> Wine Style Preference

1. Red - Light & Fruity(610)
2. Red - Smooth & Supple(611)
3. Red - Earthy & Spicy(612)
4. Red - Big & Bold(613)
5. White - Fruity & Smooth(615)
6. White - Rich & Creamy(616)
7. White - Light & Crisp(614)
8. Sweet(617)

> Region Preference ( we can get a list of region here)

1. California(101)
2. Washington(104)

> Appellation ( we can get a list here if we need)

1. Champane(2331)
2. Chile(2428)
3. Austria(607)

> Publication ( In that publication the wine was presented)

1. Wine Spectator
2. Wine Advocate

>Product Attributes(  we can get a complete list here..)

1. Magnums and Larger(15418)
2. Half bottles(42)
3. Great bottles to give(15419)

>Vintage ( we can get a list here too...)

1. 1952(320)
2. 1945(315)
3. Non-Vintage(37)

> Food Type ( 

1. Meat(3008)
2. Cheese(3009)
3. Dessert(3010)
4. Pasta and Grains(3012)
5. Poultry(3013)
6. Seafood(3014)

**Comment by megh0682** [comment]
**API ENDPOINTS**

[ ] - Root level category for wine finder

`curl -X GET -H "term: mondavi" -H "size: 5" -H "offset: 0" -H "apikey: 007fe7ab34275330c97077856e7a5644" -H "Cache-Control: no-cache" -H "Postman-Token: 439f5548-d00a-91e6-a852-0014037f0f5d" "http://services.wine.com/api/beta2/service.svc/json/categorymap?/categorymap?filter=categories(490)&apikey=007fe7ab34275330c97077856e7a5644"
`
```
{
  "Status": {
    "Messages": [],
    "ReturnCode": 0
  },
  "Categories": [
    {
      "Description": "",
      "Id": 3000,
      "Name": "Food Type",
      "Refinements": [
        {
          "Description": "",
          "Id": 3008,
          "Name": "Meat",
          "Url": ""
        },
        {
          "Description": "",
          "Id": 3009,
          "Name": "Cheese",
          "Url": ""
        },
        {
          "Description": "",
          "Id": 3010,
          "Name": "Dessert",
          "Url": ""
        },
        {
          "Description": "",
          "Id": 3012,
          "Name": "Pasta & Grains",
          "Url": ""
        },
        {
          "Description": "",
          "Id": 3013,
          "Name": "Poultry",
          "Url": ""
        },
        {
          "Description": "",
          "Id": 3014,
          "Name": "Seafood",
          "Url": ""
        }
      ]
    }
  ]
}
```

**Comment by monicaj314** [comment]
For Wine Types, we should allow the user to search wine by Red, White, Rose, and Sparkling types.
I believe it would be too complex to include all varietal types as individual input fields, which would also severely clutter up the UI.

Wine Style Preferences can be simplified to Light, Fruity, Crisp, Smooth, Earth/Spicy, Bold, and Rich/Creamy (7 input options). If the user selects "Light" we can include results for both "Red - Light & Fruity" and "White - Light & Crisp" (So if the user selects "White" + "Light", we would include only results for "White - Light & Crisp").

I'm open to how we should approach region, because there are so many. I think we can limit the input selections to US, Europe, South America, and Australia/New Zealand, and find a way to grab results which would include all the applicable regions.

Parameters to leave out for the sake of simplicity:
Appellation
Publication
Vintage
Food Type (for now)
